[package]
name = "http-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["macros"] }
tokio = { version = "1", features = ["full"] }
tokio-util = "*"
tower = "0.5"
hyper = { version = "1", features = ["full", "client"] }
hyper-util = { version = "0.1", features = ["full"] }
futures-util = "0.3"
futures = "0.3.31"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_derive = "1"
toml = "0.8"
async-compression = { version = "0.4.32", features = [
    "gzip",
    "zstd",
    "all-implementations",
] }
http-body-util = "*"
clap = { version = "*", features = ["derive"] }
mimalloc = { version = "*", features = ["v3"] }
rand = "0.9.2"
log = "0.4.29"
log4rs = "*"
async-stream = "0.3.6"
thiserror = "2.0.17"

opendal = { version = "0.55", features = ["services-fs"] }
bytes = "1"
s3s = { version = "*", features = ["tower"]}
async-trait = "*"

# 官方核心库，非常稳健
aws-sigv4 = "1.2"
aws-credential-types = "1.2"
# 辅助库
sha2 = "0.10"
hex = "0.4"
time = "0.3"
http = "1.0"
regex = "1.10"
url = "*"

chrono = { version = "*", features = ["serde"]}
uuid = "*"
sqlx = { version = "0.8.6", features = ["sqlite", "uuid", "time", "chrono"]}
strum = "*"
strum_macros = "*"
