[package]
name = "http-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
pingora = {version="0.6.0", features=["proxy"]}
async-trait = "0.1.89"
bytes = "*"
http = "*"
env_logger = "0.11.8"
flate2 = "1.1.2"